// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceBook.Infrastructure.Data;

#nullable disable

namespace SpaceBook.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceBook.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bookedon");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("bookingdate");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellationreason");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<bool>("EndReminderSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("endremindersent");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("endtime");

                    b.Property<string>("MeetingTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("meetingtitle");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("integer")
                        .HasColumnName("participantcount");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("roomid");

                    b.Property<bool>("StartReminderSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("startremindersent");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starttime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("BookingId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoomId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.BookingEmailNotification", b =>
                {
                    b.Property<int>("BookingEmailNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookingemailnotificationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingEmailNotificationId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("notificationtype");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sentat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("BookingEmailNotificationId");

                    b.HasIndex("BookingId", "NotificationType")
                        .IsUnique()
                        .HasDatabaseName("ix_bookingemailnotifications_bookingid_notificationtype");

                    b.ToTable("bookingemailnotifications", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.CheckIn", b =>
                {
                    b.Property<int>("CheckInId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("checkinid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CheckInId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkedinat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("CheckInId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("checkins", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdon");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    b.HasKey("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("facilityid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FacilityId"));

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("facilityname");

                    b.HasKey("FacilityId");

                    b.ToTable("facilities", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.HotseatBooking", b =>
                {
                    b.Property<int>("HotseatBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("hotseatbookingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HotseatBookingId"));

                    b.Property<DateTime>("BookedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bookedon");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("bookingdate");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bookingstatus");

                    b.Property<DateTime?>("CheckInDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkindeadline");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checkintime");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<string>("RecordIngestedBy")
                        .HasColumnType("text")
                        .HasColumnName("recordingestedby");

                    b.Property<DateTime?>("RecordIngestedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recordingestedon");

                    b.Property<string>("RecordModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("recordmodifiedby");

                    b.Property<DateTime?>("RecordModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recordmodifiedon");

                    b.Property<DateTime?>("ReleasedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("releasedon");

                    b.Property<int>("SeatId")
                        .HasColumnType("integer")
                        .HasColumnName("seatid");

                    b.HasKey("HotseatBookingId");

                    b.HasIndex("EmployeeId", "BookingDate");

                    b.HasIndex("SeatId", "BookingDate");

                    b.ToTable("hotseatbookings", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("locationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locationname");

                    b.HasKey("LocationId");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("moduleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modulename");

                    b.Property<int>("OfficeId")
                        .HasColumnType("integer")
                        .HasColumnName("officeid");

                    b.Property<string>("RecordIngestedBy")
                        .HasColumnType("text")
                        .HasColumnName("recordingestedby");

                    b.Property<DateTime?>("RecordIngestedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recordingestedon");

                    b.Property<string>("RecordModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("recordmodifiedby");

                    b.Property<DateTime?>("RecordModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recordmodifiedon");

                    b.HasKey("ModuleId");

                    b.HasIndex("OfficeId");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notificationid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("bookingid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer")
                        .HasColumnName("employeeid");

                    b.Property<int?>("HotseatBookingId")
                        .HasColumnType("integer")
                        .HasColumnName("hotseatbookingid");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isread");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.HasKey("NotificationId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("HotseatBookingId");

                    b.HasIndex("IsRead");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("officeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfficeId"));

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("locationid");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("officename");

                    b.HasKey("OfficeId");

                    b.HasIndex("LocationId");

                    b.ToTable("offices", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("roleid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rolename");

                    b.HasKey("RoleId");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("roomid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("isblocked");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("moduleid");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("roomname");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("roomnumber");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("roomtypeid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("RoomId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.RoomFacility", b =>
                {
                    b.Property<int>("RoomFacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("roomfacilityid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomFacilityId"));

                    b.Property<int>("FacilityId")
                        .HasColumnType("integer")
                        .HasColumnName("facilityid");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("roomid");

                    b.HasKey("RoomFacilityId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("RoomId");

                    b.ToTable("roomfacilities", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.RoomType", b =>
                {
                    b.Property<int>("RoomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("roomtypeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("typename");

                    b.HasKey("RoomTypeId");

                    b.ToTable("roomtypes", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("seatid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SeatId"));

                    b.Property<int>("ColumnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("columnnumber");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isactive");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("moduleid");

                    b.Property<string>("RowNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rownumber");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("seatnumber");

                    b.Property<string>("Section")
                        .HasColumnType("text")
                        .HasColumnName("section");

                    b.HasKey("SeatId");

                    b.HasIndex("ModuleId");

                    b.ToTable("seats", (string)null);
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Booking", b =>
                {
                    b.HasOne("SpaceBook.Domain.Entities.Employee", "Employee")
                        .WithMany("Bookings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpaceBook.Domain.Entities.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.BookingEmailNotification", b =>
                {
                    b.HasOne("SpaceBook.Domain.Entities.Booking", "Booking")
                        .WithMany("EmailNotifications")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("SpaceBook.Domain.Entities.Booking", "Booking")
                        .WithOne("CheckIn")
                        .HasForeignKey("SpaceBook.Domain.Entities.CheckIn", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Employee", b =>
                {
                    b.HasOne("SpaceBook.Domain.Entities.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.HotseatBooking", b =>
                {
                    b.HasOne("SpaceBook.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpaceBook.Domain.Entities.Seat", "Seat")
                        .WithMany("HotseatBookings")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Module", b =>
                {
                    b.HasOne("SpaceBook.Domain.Entities.Office", "Office")
                        .WithMany("Modules")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Notification", b =>
                {
                    b.HasOne("SpaceBook.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SpaceBook.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpaceBook.Domain.Entities.HotseatBooking", "HotseatBooking")
                        .WithMany()
                        .HasForeignKey("HotseatBookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("Employee");

                    b.Navigation("HotseatBooking");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Office", b =>
                {
                    b.HasOne("SpaceBook.Domain.Entities.Location", "Location")
                        .WithMany("Offices")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Room", b =>
                {
                    b.HasOne("SpaceBook.Domain.Entities.Module", "Module")
                        .WithMany("Rooms")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpaceBook.Domain.Entities.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.RoomFacility", b =>
                {
                    b.HasOne("SpaceBook.Domain.Entities.Facility", "Facility")
                        .WithMany("RoomFacilities")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceBook.Domain.Entities.Room", "Room")
                        .WithMany("RoomFacilities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facility");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Seat", b =>
                {
                    b.HasOne("SpaceBook.Domain.Entities.Module", "Module")
                        .WithMany("Seats")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Booking", b =>
                {
                    b.Navigation("CheckIn");

                    b.Navigation("EmailNotifications");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Facility", b =>
                {
                    b.Navigation("RoomFacilities");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Location", b =>
                {
                    b.Navigation("Offices");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Module", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Office", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Room", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RoomFacilities");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("SpaceBook.Domain.Entities.Seat", b =>
                {
                    b.Navigation("HotseatBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
